# Configuration du site
title: Cours de Physique 2D
description: Cours et code source sur la simulation physique en 2D
baseurl: "/ESGI_Course_2D_physics"
url: ""

# Thème
theme: jekyll-theme-cayman

# Configuration des collections
collections:
  cours:
    output: true
    permalink: /cours/:path/

# Paramètres par défaut
defaults:
  - scope:
      path: "COURS"
    values:
      layout: "default"
  - scope:
      path: "CODE"
    values:
      layout: "default"

# Inclusions
include:
  - COURS
  - CODE

# Exclusions
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - COURS.zip
  - "**/__MACOSX"

# Paramètres Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings

# Configuration pour jekyll-relative-links
relative_links:
  enabled: true
  collections: true

# Configuration pour jekyll-titles-from-headings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Configuration de la langue
lang: fr
